[package]
name = "Hello_Triangle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.20.0"
glam = "0.20.2"
stb_image = "0.2.3"
gltf = "1.0.0"